[General]
background=/home/esoc/wallpapers/1769161027550435.jpg
foreground=#d0cbc4
accent=#cc9b6a
surface=#272729
muted=#6e6a65
success=#6a9955
failure=#a04040
warning=#bf7845
font=JetBrainsMono Nerd Font
fontSize=14
